version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
      
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - echo "building my code"
  post_build:
    commands:
      - echo "push my image"
